In [8]:
import pandas as pd
import numpy as np
import pymongo as pygo
import urllib.parse
from pymongo import MongoClient

## Connecting Mongodb Atlas

In [10]:
username = "Dinesh24"
password = "Din@9600"
# Escape username and password
escaped_username = urllib.parse.quote_plus(username)
escaped_password = urllib.parse.quote_plus(password)
# Construct the connection string with escaped username and password
connection_string = f"mongodb+srv://{escaped_username}:{escaped_password}@cluster0.qav8w7p.mongodb.net/?retryWrites=true&w=majority"
# Create a MongoClient
client = MongoClient(connection_string)
# Access the database and collection
db = client.sample_airbnb
col = db.listingsAndReviews

# working with the Airbnb dataset in MongoDB using PyMongo

In [12]:
rel_data = []
for i in col.find():
    data = dict(Id = i['_id'],
                Name = i.get('name'),
                Description = i['description'],
                Property_type = i['property_type'],
                Room_type = i['room_type'],
                Bed_type = i['bed_type'],
                Min_nights = int(i['minimum_nights']),
                Max_nights = (i['maximum_nights']),
                Cancellation_policy = i['cancellation_policy'],
                Accomodates = i['accommodates'],
                Total_bedrooms = i.get('bedrooms'),
                Total_beds =  i.get('beds'),
                Availability_365 = i['availability']['availability_365'],
                Price = i['price'],
                calculated_host_listing_count = i['host']['host_listings_count'],
                neighbourhood = i['host']['host_neighbourhood'],
                No_of_reviews = i['number_of_reviews'],
                Review_scores = i['review_scores'].get('review_scores_rating'),
                Amenities = ', '.join(i['amenities']),
                Host_id = i['host']['host_id'],
                Host_name = i['host']['host_name'],
                Street = i['address']['street'],
                Country = i['address']['country'],
                Country_code = i['address']['country_code'],
                Location_type = i['address']['location']['type'],
                Longitude = i['address']['location']['coordinates'][0],
                Latitude = i['address']['location']['coordinates'][1])
    rel_data.append(data)

In [13]:
DF = pd.DataFrame(rel_data)

In [14]:
DF

,Id,Name,Description,Property_type,Room_type,Bed_type,Min_nights,Max_nights,Cancellation_policy,Accomodates,...,Review_scores,Amenities,Host_id,Host_name,Street,Country,Country_code,Location_type,Longitude,Latitude
0,10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,House,Entire home/apt,Real Bed,2,30,moderate,8,...,89.0,"TV, Cable TV, Wifi, Kitchen, Paid parking off ...",51399391,Ana&Gon√ßalo,"Porto, Porto, Portugal",Portugal,PT,Point,-8.613080,41.141300
1,10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Apartment,Entire home/apt,Real Bed,2,1125,flexible,4,...,NaN,"Wifi, Wheelchair accessible, Kitchen, Free par...",1282196,Ynaie,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.230750,-22.966254
2,1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,...,84.0,"TV, Cable TV, Wifi, Air conditioning, Pool, Ki...",5448114,David,"Honolulu, HI, United States",United States,US,Point,-157.839190,21.286340
3,10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,Apartment,Private room,Real Bed,14,1125,flexible,1,...,100.0,"Internet, Wifi, Air conditioning, Kitchen, Buz...",11275734,Josh,"Brooklyn, NY, United States",United States,US,Point,-73.936150,40.697910
4,10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,Apartment,Private room,Real Bed,1,1125,flexible,2,...,NaN,"TV, Cable TV, Internet, Wifi, Air conditioning...",51496939,Livia,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.205047,-22.971951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,Cozy apartment downtown Porto,"Renovated, fully equipped, within walking dist...",Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,4,...,98.0,"TV, Cable TV, Internet, Wifi, Kitchen, Paid pa...",37776205,Ana,"Porto, Porto, Portugal",Portugal,PT,Point,-8.616930,41.151370
5551,9985696,Kadƒ±k√∂y-Altƒ±yol,Kadƒ±k√∂y merkezde 2+1 dairem vardƒ±r.√áok kalabal...,House,Entire home/apt,Real Bed,1,1125,flexible,2,...,NaN,"TV, Cable TV, Internet, Wifi, Kitchen, Buzzer/...",51303748,Eren,"Kadƒ±k√∂y, ƒ∞stanbul, Turkey",Turkey,TR,Point,29.030790,40.985630
5552,9987200,The best suite in Copacabana (total privacy),Excellent private suite with bathroom at the A...,Aparthotel,Private room,Real Bed,3,60,flexible,3,...,97.0,"TV, Cable TV, Wifi, Air conditioning, Pool, Gy...",51314789,Dumont,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.176533,-22.961076
5553,9990304,March Madness Special! Aina Nalu Platinum D107,Walk out to Saltwater Infinity Pool! Call us N...,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,...,97.0,"TV, Cable TV, Wifi, Air conditioning, Wheelcha...",51013381,Coconut Condos,"Lahaina, HI, United States",United States,US,Point,-156.676460,20.875610
5554,9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,...,92.0,"TV, Wifi, Air conditioning, Pool, Kitchen, Fre...",51013381,Coconut Condos,"Lahaina, HI, United States",United States,US,Point,-156.667520,20.858940

In [15]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Id                             5555 non-null   object
 1   Name                           5555 non-null   object
 2   Description                    5555 non-null   object
 3   Property_type                  5555 non-null   object
 4   Room_type                      5555 non-null   object
 5   Bed_type                       5555 non-null   object
 6   Min_nights                     5555 non-null   int64
 7   Max_nights                     5555 non-null   object
 8   Cancellation_policy            5555 non-null   object
 9   Accomodates                    5555 non-null   int64
 10  Total_bedrooms                 5550 non-null   float64
 11  Total_beds                     5542 non-null   float64
 12  Availability_365               5555 non-null   int64
 13  Price                          5555 non-null   object
 14  calculated_host_listing_count  5555 non-null   int64
 15  neighbourhood                  5555 non-null   object
 16  No_of_reviews                  5555 non-null   int64
 17  Review_scores                  4081 non-null   float64
 18  Amenities                      5555 non-null   object
 19  Host_id                        5555 non-null   object
 20  Host_name                      5555 non-null   object
 21  Street                         5555 non-null   object
 22  Country                        5555 non-null   object
 23  Country_code                   5555 non-null   object
 24  Location_type                  5555 non-null   object
 25  Longitude                      5555 non-null   float64
 26  Latitude                       5555 non-null   float64
dtypes: float64(5), int64(5), object(17)
memory usage: 1.1+ MB

In [16]:
DF.columns

Index(['Id', 'Name', 'Description', 'Property_type', 'Room_type', 'Bed_type',
       'Min_nights', 'Max_nights', 'Cancellation_policy', 'Accomodates',
       'Total_bedrooms', 'Total_beds', 'Availability_365', 'Price',
       'calculated_host_listing_count', 'neighbourhood', 'No_of_reviews',
       'Review_scores', 'Amenities', 'Host_id', 'Host_name', 'Street',
       'Country', 'Country_code', 'Location_type', 'Longitude', 'Latitude'],
      dtype='object')

In [22]:
DF.isnull().sum()

Id                                  0
Name                                0
Description                         0
Property_type                       0
Room_type                           0
Bed_type                            0
Min_nights                          0
Max_nights                          0
Cancellation_policy                 0
Accomodates                         0
Total_bedrooms                      5
Total_beds                         13
Availability_365                    0
Price                               0
calculated_host_listing_count       0
neighbourhood                       0
No_of_reviews                       0
Review_scores                    1474
Amenities                           0
Host_id                             0
Host_name                           0
Street                              0
Country                             0
Country_code                        0
Location_type                       0
Longitude                           0
Latitude                            0
dtype: int64

In [19]:
DF.Price = DF.Price.astype(str).astype(float)
DF.Review_scores = DF.Review_scores.astype('Int64')

In [20]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Id                             5555 non-null   object
 1   Name                           5555 non-null   object
 2   Description                    5555 non-null   object
 3   Property_type                  5555 non-null   object
 4   Room_type                      5555 non-null   object
 5   Bed_type                       5555 non-null   object
 6   Min_nights                     5555 non-null   int64
 7   Max_nights                     5555 non-null   object
 8   Cancellation_policy            5555 non-null   object
 9   Accomodates                    5555 non-null   int64
 10  Total_bedrooms                 5550 non-null   float64
 11  Total_beds                     5542 non-null   float64
 12  Availability_365               5555 non-null   int64
 13  Price                          5555 non-null   float64
 14  calculated_host_listing_count  5555 non-null   int64
 15  neighbourhood                  5555 non-null   object
 16  No_of_reviews                  5555 non-null   int64
 17  Review_scores                  4081 non-null   Int64
 18  Amenities                      5555 non-null   object
 19  Host_id                        5555 non-null   object
 20  Host_name                      5555 non-null   object
 21  Street                         5555 non-null   object
 22  Country                        5555 non-null   object
 23  Country_code                   5555 non-null   object
 24  Location_type                  5555 non-null   object
 25  Longitude                      5555 non-null   float64
 26  Latitude                       5555 non-null   float64
dtypes: Int64(1), float64(5), int64(5), object(16)
memory usage: 1.1+ MB

# filling null value

In [24]:
DF.Total_bedrooms.fillna(DF.Total_bedrooms.mode()[0],inplace=True)
DF.Total_beds.fillna(DF.Total_beds.median(),inplace= True)
DF.Review_scores.fillna(DF.Review_scores.median(),inplace=True)

In [26]:
DF.isna().sum()

Id                               0
Name                             0
Description                      0
Property_type                    0
Room_type                        0
Bed_type                         0
Min_nights                       0
Max_nights                       0
Cancellation_policy              0
Accomodates                      0
Total_bedrooms                   0
Total_beds                       0
Availability_365                 0
Price                            0
calculated_host_listing_count    0
neighbourhood                    0
No_of_reviews                    0
Review_scores                    0
Amenities                        0
Host_id                          0
Host_name                        0
Street                           0
Country                          0
Country_code                     0
Location_type                    0
Longitude                        0
Latitude                         0
dtype: int64

In [29]:
#checking Duplicate records
DF[DF.duplicated]

Empty DataFrame
Columns: [Id, Name, Description, Property_type, Room_type, Bed_type, Min_nights, Max_nights, Cancellation_policy, Accomodates, Total_bedrooms, Total_beds, Availability_365, Price, calculated_host_listing_count, neighbourhood, No_of_reviews, Review_scores, Amenities, Host_id, Host_name, Street, Country, Country_code, Location_type, Longitude, Latitude]
Index: []

[0 rows x 27 columns]

In [32]:
DF['Country'].unique()

array(['Portugal', 'Brazil', 'United States', 'Turkey', 'Canada',
       'Hong Kong', 'Spain', 'Australia', 'China'], dtype=object)

In [33]:
DF['neighbourhood'].replace("","Copacabana",inplace=True)

In [34]:
DF.reset_index(drop=True,inplace=True)

In [35]:
DF

,Id,Name,Description,Property_type,Room_type,Bed_type,Min_nights,Max_nights,Cancellation_policy,Accomodates,...,Review_scores,Amenities,Host_id,Host_name,Street,Country,Country_code,Location_type,Longitude,Latitude
0,10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,House,Entire home/apt,Real Bed,2,30,moderate,8,...,89,"TV, Cable TV, Wifi, Kitchen, Paid parking off ...",51399391,Ana&Gon√ßalo,"Porto, Porto, Portugal",Portugal,PT,Point,-8.613080,41.141300
1,10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Apartment,Entire home/apt,Real Bed,2,1125,flexible,4,...,95,"Wifi, Wheelchair accessible, Kitchen, Free par...",1282196,Ynaie,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.230750,-22.966254
2,1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,...,84,"TV, Cable TV, Wifi, Air conditioning, Pool, Ki...",5448114,David,"Honolulu, HI, United States",United States,US,Point,-157.839190,21.286340
3,10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,Apartment,Private room,Real Bed,14,1125,flexible,1,...,100,"Internet, Wifi, Air conditioning, Kitchen, Buz...",11275734,Josh,"Brooklyn, NY, United States",United States,US,Point,-73.936150,40.697910
4,10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,Apartment,Private room,Real Bed,1,1125,flexible,2,...,95,"TV, Cable TV, Internet, Wifi, Air conditioning...",51496939,Livia,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.205047,-22.971951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9983221,Cozy apartment downtown Porto,"Renovated, fully equipped, within walking dist...",Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,4,...,98,"TV, Cable TV, Internet, Wifi, Kitchen, Paid pa...",37776205,Ana,"Porto, Porto, Portugal",Portugal,PT,Point,-8.616930,41.151370
5551,9985696,Kadƒ±k√∂y-Altƒ±yol,Kadƒ±k√∂y merkezde 2+1 dairem vardƒ±r.√áok kalabal...,House,Entire home/apt,Real Bed,1,1125,flexible,2,...,95,"TV, Cable TV, Internet, Wifi, Kitchen, Buzzer/...",51303748,Eren,"Kadƒ±k√∂y, ƒ∞stanbul, Turkey",Turkey,TR,Point,29.030790,40.985630
5552,9987200,The best suite in Copacabana (total privacy),Excellent private suite with bathroom at the A...,Aparthotel,Private room,Real Bed,3,60,flexible,3,...,97,"TV, Cable TV, Wifi, Air conditioning, Pool, Gy...",51314789,Dumont,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,Point,-43.176533,-22.961076
5553,9990304,March Madness Special! Aina Nalu Platinum D107,Walk out to Saltwater Infinity Pool! Call us N...,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,...,97,"TV, Cable TV, Wifi, Air conditioning, Wheelcha...",51013381,Coconut Condos,"Lahaina, HI, United States",United States,US,Point,-156.676460,20.875610
5554,9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,...,92,"TV, Wifi, Air conditioning, Pool, Kitchen, Fre...",51013381,Coconut Condos,"Lahaina, HI, United States",United States,US,Point,-156.667520,20.858940

In [36]:
DF['neighbourhood'].value_counts()

neighbourhood
Copacabana                   2047
Le Plateau                    123
Mong Kok                       90
Waikiki                        76
Downtown Montreal              74
                             ...
Pointe-Claire                   1
Op√©ra - Grands Boulevards       1
Parada de Lucas                 1
San Mateo                       1
Rio Comprido                    1
Name: count, Length: 446, dtype: int64

In [37]:
DF['Country'].value_counts()

Country
United States    1222
Turkey            661
Canada            649
Spain             633
Australia         610
Brazil            606
Hong Kong         600
Portugal          555
China              19
Name: count, dtype: int64

In [38]:
DF['Property_type'].value_counts

<bound method IndexOpsMixin.value_counts of 0             House
1         Apartment
2       Condominium
3         Apartment
4         Apartment
           ...
5550      Apartment
5551          House
5552     Aparthotel
5553    Condominium
5554      Townhouse
Name: Property_type, Length: 5555, dtype: object>

In [39]:
DF['Property_type'].unique()

array(['House', 'Apartment', 'Condominium', 'Loft', 'Guesthouse',
       'Hostel', 'Serviced apartment', 'Bed and breakfast', 'Treehouse',
       'Bungalow', 'Guest suite', 'Townhouse', 'Villa', 'Cabin', 'Other',
       'Chalet', 'Farm stay', 'Boutique hotel', 'Boat', 'Cottage',
       'Earth house', 'Aparthotel', 'Resort', 'Tiny house',
       'Nature lodge', 'Hotel', 'Casa particular (Cuba)', 'Barn', 'Hut',
       'Camper/RV', 'Heritage hotel (India)', 'Pension (South Korea)',
       'Campsite', 'Houseboat', 'Castle', 'Train'], dtype=object)

In [40]:
DF['Room_type'].value_counts()

Room_type
Entire home/apt    3489
Private room       1983
Shared room          83
Name: count, dtype: int64

In [41]:
DF.to_csv("airbnb_DATA.csv",index=False)

In [43]:
DF['Review_scores'].value_counts()

Review_scores
95     1733
100     982
98      291
96      286
97      281
93      244
94      223
90      213
99      188
80      167
92      158
89      113
91      112
87       97
88       77
85       55
86       48
84       43
60       41
83       39
70       25
82       19
20       16
81       12
78       11
75       11
40       10
76        9
73        8
79        8
67        5
74        5
72        5
71        4
77        4
68        3
65        3
69        2
50        2
53        1
64        1
Name: count, dtype: Int64